apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
   template: 
     labels:
       app: nginx
     spec:
       containers:
       - name: c1
         image: R_IMAGE